### ISSUE TITLE
Sparkline offset in classic notebook

### ISSUE THREAD

**Issue by jtpio** [jtpio/ipyresuse#1]
The sparkline view is displayed with an offset when using the widget in the classic notebook:

![image](https://user-images.githubusercontent.com/591645/61816021-c73db100-ae4b-11e9-8dd6-6cebfd9fdd17.png)

**Comment by jtpio** [comment]
The classic notebook adds a bit of CSS for SVGs in the output area: https://github.com/jupyter/notebook/blob/e498de6775b3de57f5ff827e562c179b17893064/notebook/static/notebook/less/outputarea.less#L70-L76

```css
div.output_area svg {
    max-width: 100%;
    height: auto;
}
```
